column_names = {
    'V1': 'bandeira_origem_v1',
    'V2': 'bandeira_destino_v2',
    'V3': 'tipo_transacao_v3',
    'V4': 'tipo_transacao_2_v4',
    'V5': 'banco_origem_v5',
    'V6': 'banco_destino_v6',
    'V7': 'longitude_v7',
    'V8': 'latitude_v8',
    'V9': 'periodo_do_dia_transacao_v9',
    'V10': 'data_transacao_dia_da_semana_v10',
    'V11': 'data_transacao_mes_v11',
    'V12': 'dist_origem_destino_v12',
    'V13': 'valor_saldo_anterior_origem_v13',
    'V14': 'valor_saldo_anterior_destino_v14',
    'V15': 'tipo_cartao_v15',
    'V16': 'debito_credito_v16',
    'V17': 'tempo_conta_origem_v17',
    'V18': 'tempo_conta_destino_v18',
    'V19': 'grupo_ip_origem_v19',
    'V20': 'pais_origem_v20',
    'V21': 'pais_destino_v21',
    'V22': 'grupo_cep_origem_v22',
    'V23': 'grupo_cep_destino_v23',
    'V24': 'data_expiracao_v24',
    'V25': 'limiar_fraude_v25',
    'V26': 'bandeira_cartao_origem_v26',
    'V27': 'grupo_sistema_operacional_origem_v27',
    'V28': 'taxa_incidencia_fraudes_no_passado_v28',
    'Amount': 'Amount',
    'Time': 'Time',
    'Class': 'Fraud'
}

column_descriptions = {
    'bandeira_origem_v1': 'Código referente à bandeira de origem da transação',
    'bandeira_destino_v2': 'Código referente à bandeira de destino da transação',
    'tipo_transacao_v3': 'Tipo da transação (e.g. débito, crédito, boleto)',
    'tipo_transacao_2_v4': '',
    'banco_origem_v5': 'Código referente ao banco de origem',
    'banco_destino_v6': 'Código referente ao banco de destino',
    'longitude_v7': '',
    'latitude_v8': '',
    'periodo_do_dia_transacao_v9': '',
    'data_transacao_dia_da_semana_v10': '',
    'data_transacao_mes_v11': '',
    'dist_origem_destino_v12': '',
    'valor_saldo_anterior_origem_v13': '',
    'valor_saldo_anterior_destino_v14': '',
    'tipo_cartao_v15': '',
    'debito_credito_v16': '',
    'tempo_conta_origem_v17': '',
    'tempo_conta_destino_v18': '',
    'grupo_ip_origem_v19': '',
    'pais_origem_v20': '',
    'pais_destino_v21': '',
    'grupo_cep_origem_v22': '',
    'grupo_cep_destino_v23': '',
    'data_expiracao_v24': '',
    'limiar_fraude_v25': '',
    'bandeira_cartao_origem_v26': '',
    'grupo_sistema_operacional_origem_v27': '',
    'taxa_incidencia_fraudes_no_passado_v28': '',
    'Amount': '',
    'Time': '',
    'Fraud': '',
}